--
-- PostgreSQL database dump
--

-- Dumped from database version 17.4 (Homebrew)
-- Dumped by pg_dump version 17.2

-- Started on 2026-05-03 23:28:20 +07

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 220 (class 1259 OID 33230)
-- Name: app_role; Type: TABLE; Schema: public; Owner: a1
--

CREATE TABLE public.app_role (
    id smallint NOT NULL,
    code character varying(50) NOT NULL,
    name character varying(100) NOT NULL,
    description text,
    priority smallint DEFAULT 100 NOT NULL,
    permissions jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.app_role OWNER TO a1;

--
-- TOC entry 221 (class 1259 OID 33238)
-- Name: app_role_id_seq; Type: SEQUENCE; Schema: public; Owner: a1
--

ALTER TABLE public.app_role ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.app_role_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 222 (class 1259 OID 33239)
-- Name: app_user; Type: TABLE; Schema: public; Owner: a1
--

CREATE TABLE public.app_user (
    id bigint NOT NULL,
    role_id smallint NOT NULL,
    email public.citext NOT NULL,
    password_hash text NOT NULL,
    display_name character varying(150) NOT NULL,
    preferred_language_id smallint,
    avatar_url text,
    is_active boolean DEFAULT true NOT NULL,
    is_verified boolean DEFAULT false NOT NULL,
    registered_at timestamp with time zone DEFAULT now() NOT NULL,
    last_login_at timestamp with time zone,
    extra_metadata jsonb DEFAULT '{}'::jsonb NOT NULL
);


ALTER TABLE public.app_user OWNER TO a1;

--
-- TOC entry 223 (class 1259 OID 33248)
-- Name: app_user_id_seq; Type: SEQUENCE; Schema: public; Owner: a1
--

ALTER TABLE public.app_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.app_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 224 (class 1259 OID 33249)
-- Name: article; Type: TABLE; Schema: public; Owner: a1
--

CREATE TABLE public.article (
    id bigint NOT NULL,
    article_type character varying(30) NOT NULL,
    author_user_id bigint,
    original_source_id bigint,
    reading_time_min integer,
    is_featured boolean DEFAULT false NOT NULL,
    extra_metadata jsonb DEFAULT '{}'::jsonb NOT NULL
);


ALTER TABLE public.article OWNER TO a1;

--
-- TOC entry 225 (class 1259 OID 33256)
-- Name: article_entity_link; Type: TABLE; Schema: public; Owner: a1
--

CREATE TABLE public.article_entity_link (
    article_id bigint NOT NULL,
    entity_id bigint NOT NULL,
    link_type public.article_link_type DEFAULT 'about'::public.article_link_type NOT NULL,
    link_weight numeric(4,2) DEFAULT 1.00 NOT NULL,
    confidence numeric(3,2) DEFAULT 1.00 NOT NULL,
    source_id bigint,
    note text,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.article_entity_link OWNER TO a1;

--
-- TOC entry 226 (class 1259 OID 33265)
-- Name: audit_log; Type: TABLE; Schema: public; Owner: a1
--

CREATE TABLE public.audit_log (
    id bigint NOT NULL,
    user_id bigint,
    entity_id bigint,
    action character varying(100) NOT NULL,
    table_name character varying(128),
    record_pk character varying(128),
    ip_address inet,
    user_agent text,
    old_data jsonb,
    new_data jsonb,
    context jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.audit_log OWNER TO a1;

--
-- TOC entry 227 (class 1259 OID 33272)
-- Name: audit_log_id_seq; Type: SEQUENCE; Schema: public; Owner: a1
--

ALTER TABLE public.audit_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.audit_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 270 (class 1259 OID 34390)
-- Name: award; Type: TABLE; Schema: public; Owner: a1
--

CREATE TABLE public.award (
    id bigint NOT NULL,
    code character varying(64) NOT NULL,
    kind public.award_kind DEFAULT 'festival'::public.award_kind NOT NULL,
    country_code character varying(8),
    founded_year smallint,
    is_active boolean DEFAULT true NOT NULL,
    official_url text,
    extra_metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT award_founded_year_reasonable CHECK (((founded_year IS NULL) OR ((founded_year >= 1880) AND (founded_year <= 2100))))
);


ALTER TABLE public.award OWNER TO a1;

--
-- TOC entry 273 (class 1259 OID 34424)
-- Name: award_category; Type: TABLE; Schema: public; Owner: a1
--

CREATE TABLE public.award_category (
    id bigint NOT NULL,
    award_id bigint NOT NULL,
    code character varying(64) NOT NULL,
    target_entity_type public.entity_type,
    is_active boolean DEFAULT true NOT NULL,
    sort_order integer DEFAULT 0 NOT NULL,
    extra_metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.award_category OWNER TO a1;

--
-- TOC entry 272 (class 1259 OID 34423)
-- Name: award_category_id_seq; Type: SEQUENCE; Schema: public; Owner: a1
--

ALTER TABLE public.award_category ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.award_category_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 274 (class 1259 OID 34442)
-- Name: award_category_translation; Type: TABLE; Schema: public; Owner: a1
--

CREATE TABLE public.award_category_translation (
    category_id bigint NOT NULL,
    language_id smallint NOT NULL,
    name character varying(255) NOT NULL,
    description text,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.award_category_translation OWNER TO a1;

--
-- TOC entry 276 (class 1259 OID 34461)
-- Name: award_ceremony; Type: TABLE; Schema: public; Owner: a1
--

CREATE TABLE public.award_ceremony (
    id bigint NOT NULL,
    award_id bigint NOT NULL,
    edition_number integer,
    year smallint NOT NULL,
    ceremony_date date,
    location character varying(255),
    host_persons bigint[] DEFAULT ARRAY[]::bigint[],
    extra_metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT award_ceremony_year_reasonable CHECK (((year >= 1880) AND (year <= 2100)))
);


ALTER TABLE public.award_ceremony OWNER TO a1;

--
-- TOC entry 275 (class 1259 OID 34460)
-- Name: award_ceremony_id_seq; Type: SEQUENCE; Schema: public; Owner: a1
--

ALTER TABLE public.award_ceremony ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.award_ceremony_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 269 (class 1259 OID 34389)
-- Name: award_id_seq; Type: SEQUENCE; Schema: public; Owner: a1
--

ALTER TABLE public.award ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.award_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 278 (class 1259 OID 34481)
-- Name: award_nomination; Type: TABLE; Schema: public; Owner: a1
--

CREATE TABLE public.award_nomination (
    id bigint NOT NULL,
    ceremony_id bigint NOT NULL,
    category_id bigint NOT NULL,
    entity_id bigint NOT NULL,
    person_id bigint,
    status public.nomination_status DEFAULT 'nominated'::public.nomination_status NOT NULL,
    note text,
    source_id bigint,
    confidence numeric(3,2) DEFAULT 1.00 NOT NULL,
    created_by_user_id bigint,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT award_nomination_confidence_range CHECK (((confidence >= (0)::numeric) AND (confidence <= (1)::numeric)))
);


ALTER TABLE public.award_nomination OWNER TO a1;

--
-- TOC entry 277 (class 1259 OID 34480)
-- Name: award_nomination_id_seq; Type: SEQUENCE; Schema: public; Owner: a1
--

ALTER TABLE public.award_nomination ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.award_nomination_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 271 (class 1259 OID 34405)
-- Name: award_translation; Type: TABLE; Schema: public; Owner: a1
--

CREATE TABLE public.award_translation (
    award_id bigint NOT NULL,
    language_id smallint NOT NULL,
    name character varying(255) NOT NULL,
    short_name character varying(100),
    description text,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.award_translation OWNER TO a1;

--
-- TOC entry 228 (class 1259 OID 33273)
-- Name: cluster_influence; Type: TABLE; Schema: public; Owner: a1
--

CREATE TABLE public.cluster_influence (
    id bigint NOT NULL,
    source_cluster_id bigint NOT NULL,
    target_cluster_id bigint NOT NULL,
    weight smallint DEFAULT 3 NOT NULL,
    confidence numeric(3,2) DEFAULT 0.50 NOT NULL,
    influence_aspects public.influence_aspect[] DEFAULT ARRAY[]::public.influence_aspect[] NOT NULL,
    relation_note text,
    inferred_by_system boolean DEFAULT false NOT NULL,
    created_by_user_id bigint,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT cluster_influence_confidence_range CHECK (((confidence >= (0)::numeric) AND (confidence <= (1)::numeric))),
    CONSTRAINT cluster_influence_no_self CHECK ((source_cluster_id <> target_cluster_id)),
    CONSTRAINT cluster_influence_weight_range CHECK (((weight >= 1) AND (weight <= 5)))
);


ALTER TABLE public.cluster_influence OWNER TO a1;

--
-- TOC entry 229 (class 1259 OID 33287)
-- Name: cluster_influence_id_seq; Type: SEQUENCE; Schema: public; Owner: a1
--

ALTER TABLE public.cluster_influence ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cluster_influence_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 230 (class 1259 OID 33288)
-- Name: collection; Type: TABLE; Schema: public; Owner: a1
--

CREATE TABLE public.collection (
    id bigint NOT NULL,
    owner_user_id bigint,
    kind public.collection_kind DEFAULT 'custom'::public.collection_kind NOT NULL,
    is_system boolean DEFAULT false NOT NULL,
    cover_entity_id bigint,
    items_count integer DEFAULT 0 NOT NULL,
    extra_metadata jsonb DEFAULT '{}'::jsonb NOT NULL
);


ALTER TABLE public.collection OWNER TO a1;

--
-- TOC entry 231 (class 1259 OID 33297)
-- Name: collection_item; Type: TABLE; Schema: public; Owner: a1
--

CREATE TABLE public.collection_item (
    collection_id bigint NOT NULL,
    entity_id bigint NOT NULL,
    "position" integer DEFAULT 1 NOT NULL,
    note text,
    added_by_user_id bigint,
    added_at timestamp with time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.collection_item OWNER TO a1;

--
-- TOC entry 232 (class 1259 OID 33304)
-- Name: director_cluster; Type: TABLE; Schema: public; Owner: a1
--

CREATE TABLE public.director_cluster (
    id bigint NOT NULL,
    code character varying(64) NOT NULL,
    kind public.cluster_kind DEFAULT 'movement'::public.cluster_kind NOT NULL,
    period_start smallint,
    period_end smallint,
    country_code character varying(8),
    is_active boolean DEFAULT true NOT NULL,
    extra_metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_by_user_id bigint,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT director_cluster_period_order CHECK (((period_end IS NULL) OR (period_start IS NULL) OR (period_end >= period_start))),
    CONSTRAINT director_cluster_period_reasonable CHECK ((((period_start IS NULL) OR ((period_start >= 1880) AND (period_start <= 2100))) AND ((period_end IS NULL) OR ((period_end >= 1880) AND (period_end <= 2100)))))
);


ALTER TABLE public.director_cluster OWNER TO a1;

--
-- TOC entry 233 (class 1259 OID 33316)
-- Name: director_cluster_id_seq; Type: SEQUENCE; Schema: public; Owner: a1
--

ALTER TABLE public.director_cluster ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.director_cluster_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 234 (class 1259 OID 33317)
-- Name: director_cluster_member; Type: TABLE; Schema: public; Owner: a1
--

CREATE TABLE public.director_cluster_member (
    cluster_id bigint NOT NULL,
    director_id bigint NOT NULL,
    joined_year smallint,
    left_year smallint,
    is_core boolean DEFAULT false NOT NULL,
    role_note text,
    confidence numeric(3,2) DEFAULT 1.00 NOT NULL,
    source_id bigint,
    added_by_user_id bigint,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT director_cluster_member_confidence CHECK (((confidence >= (0)::numeric) AND (confidence <= (1)::numeric))),
    CONSTRAINT director_cluster_member_year_order CHECK (((left_year IS NULL) OR (joined_year IS NULL) OR (left_year >= joined_year)))
);


ALTER TABLE public.director_cluster_member OWNER TO a1;

--
-- TOC entry 235 (class 1259 OID 33327)
-- Name: director_cluster_translation; Type: TABLE; Schema: public; Owner: a1
--

CREATE TABLE public.director_cluster_translation (
    cluster_id bigint NOT NULL,
    language_id smallint NOT NULL,
    name character varying(255) NOT NULL,
    description text,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.director_cluster_translation OWNER TO a1;

--
-- TOC entry 236 (class 1259 OID 33333)
-- Name: director_influence; Type: TABLE; Schema: public; Owner: a1
--

CREATE TABLE public.director_influence (
    id bigint NOT NULL,
    source_director_id bigint NOT NULL,
    target_director_id bigint NOT NULL,
    weight smallint DEFAULT 3 NOT NULL,
    confidence numeric(3,2) DEFAULT 0.50 NOT NULL,
    relation_note text,
    inferred_by_system boolean DEFAULT false NOT NULL,
    created_by_user_id bigint,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    influence_period_start smallint,
    influence_period_end smallint,
    influence_aspects public.influence_aspect[] DEFAULT ARRAY[]::public.influence_aspect[] NOT NULL,
    key_film_id bigint,
    is_acknowledged boolean DEFAULT false NOT NULL,
    CONSTRAINT director_influence_check CHECK ((source_director_id <> target_director_id)),
    CONSTRAINT director_influence_confidence_check CHECK (((confidence >= (0)::numeric) AND (confidence <= (1)::numeric))),
    CONSTRAINT director_influence_period_order CHECK (((influence_period_end IS NULL) OR (influence_period_start IS NULL) OR (influence_period_end >= influence_period_start))),
    CONSTRAINT director_influence_period_reasonable CHECK ((((influence_period_start IS NULL) OR ((influence_period_start >= 1880) AND (influence_period_start <= 2100))) AND ((influence_period_end IS NULL) OR ((influence_period_end >= 1880) AND (influence_period_end <= 2100))))),
    CONSTRAINT director_influence_weight_check CHECK (((weight >= 1) AND (weight <= 5)))
);


ALTER TABLE public.director_influence OWNER TO a1;

--
-- TOC entry 237 (class 1259 OID 33350)
-- Name: director_influence_id_seq; Type: SEQUENCE; Schema: public; Owner: a1
--

ALTER TABLE public.director_influence ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.director_influence_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 238 (class 1259 OID 33351)
-- Name: director_influence_source; Type: TABLE; Schema: public; Owner: a1
--

CREATE TABLE public.director_influence_source (
    influence_id bigint NOT NULL,
    source_id bigint NOT NULL,
    evidence_text text,
    pages character varying(50),
    url_fragment text,
    confidence numeric(3,2) DEFAULT 0.50 NOT NULL,
    is_primary boolean DEFAULT false NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.director_influence_source OWNER TO a1;

--
-- TOC entry 239 (class 1259 OID 33359)
-- Name: person; Type: TABLE; Schema: public; Owner: a1
--

CREATE TABLE public.person (
    id bigint NOT NULL,
    birth_date date,
    death_date date,
    birth_place text,
    is_director boolean DEFAULT false NOT NULL,
    is_actor boolean DEFAULT false NOT NULL,
    primary_profession character varying(100),
    gender character varying(30),
    sort_name character varying(255),
    extra_metadata jsonb DEFAULT '{}'::jsonb NOT NULL
);


ALTER TABLE public.person OWNER TO a1;

--
-- TOC entry 241 (class 1259 OID 33374)
-- Name: entity; Type: TABLE; Schema: public; Owner: a1
--

CREATE TABLE public.entity (
    id bigint NOT NULL,
    entity_type public.entity_type NOT NULL,
    status public.publication_status DEFAULT 'draft'::public.publication_status NOT NULL,
    access_level public.access_level DEFAULT 'public'::public.access_level NOT NULL,
    primary_image_url text,
    thumbnail_url text,
    official_url text,
    external_ids jsonb DEFAULT '{}'::jsonb NOT NULL,
    extra_metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_by_user_id bigint,
    updated_by_user_id bigint,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    published_at timestamp with time zone
);


ALTER TABLE public.entity OWNER TO a1;

--
-- TOC entry 242 (class 1259 OID 33385)
-- Name: entity_id_seq; Type: SEQUENCE; Schema: public; Owner: a1
--

ALTER TABLE public.entity ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.entity_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 243 (class 1259 OID 33386)
-- Name: entity_media; Type: TABLE; Schema: public; Owner: a1
--

CREATE TABLE public.entity_media (
    entity_id bigint NOT NULL,
    media_id bigint NOT NULL,
    role public.media_role NOT NULL,
    is_primary boolean DEFAULT false NOT NULL,
    "position" integer DEFAULT 0 NOT NULL,
    note text,
    added_by_user_id bigint,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.entity_media OWNER TO a1;

--
-- TOC entry 284 (class 1259 OID 34595)
-- Name: entity_relation; Type: TABLE; Schema: public; Owner: a1
--

CREATE TABLE public.entity_relation (
    id bigint NOT NULL,
    source_entity_id bigint NOT NULL,
    target_entity_id bigint NOT NULL,
    relation_kind public.entity_relation_kind NOT NULL,
    is_bidirectional boolean DEFAULT false NOT NULL,
    weight smallint DEFAULT 3 NOT NULL,
    confidence numeric(3,2) DEFAULT 1.00 NOT NULL,
    description text,
    source_id bigint,
    is_editorial boolean DEFAULT true NOT NULL,
    created_by_user_id bigint,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT entity_relation_confidence_range CHECK (((confidence >= (0)::numeric) AND (confidence <= (1)::numeric))),
    CONSTRAINT entity_relation_no_self CHECK ((source_entity_id <> target_entity_id)),
    CONSTRAINT entity_relation_weight_range CHECK (((weight >= 1) AND (weight <= 5)))
);


ALTER TABLE public.entity_relation OWNER TO a1;

--
-- TOC entry 283 (class 1259 OID 34594)
-- Name: entity_relation_id_seq; Type: SEQUENCE; Schema: public; Owner: a1
--

ALTER TABLE public.entity_relation ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.entity_relation_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 244 (class 1259 OID 33394)
-- Name: entity_taxonomy; Type: TABLE; Schema: public; Owner: a1
--

CREATE TABLE public.entity_taxonomy (
    entity_id bigint NOT NULL,
    term_id bigint NOT NULL,
    is_primary boolean DEFAULT false NOT NULL,
    weight numeric(4,2) DEFAULT 1.00 NOT NULL,
    source_id bigint,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.entity_taxonomy OWNER TO a1;

--
-- TOC entry 245 (class 1259 OID 33400)
-- Name: entity_translation; Type: TABLE; Schema: public; Owner: a1
--

CREATE TABLE public.entity_translation (
    entity_id bigint NOT NULL,
    language_id smallint NOT NULL,
    search_config regconfig DEFAULT 'simple'::regconfig NOT NULL,
    slug character varying(255) NOT NULL,
    title character varying(500) NOT NULL,
    summary text,
    description text,
    body text,
    search_tsv tsvector DEFAULT ''::tsvector NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.entity_translation OWNER TO a1;

--
-- TOC entry 246 (class 1259 OID 33409)
-- Name: entity_version; Type: TABLE; Schema: public; Owner: a1
--

CREATE TABLE public.entity_version (
    id bigint NOT NULL,
    entity_id bigint NOT NULL,
    language_id smallint,
    version_no integer NOT NULL,
    change_type public.change_type DEFAULT 'update'::public.change_type NOT NULL,
    source_id bigint,
    author_user_id bigint,
    confidence numeric(3,2) DEFAULT 1.00 NOT NULL,
    snapshot jsonb DEFAULT '{}'::jsonb NOT NULL,
    comment text,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.entity_version OWNER TO a1;

--
-- TOC entry 247 (class 1259 OID 33418)
-- Name: entity_version_id_seq; Type: SEQUENCE; Schema: public; Owner: a1
--

ALTER TABLE public.entity_version ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.entity_version_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 248 (class 1259 OID 33419)
-- Name: favorite; Type: TABLE; Schema: public; Owner: a1
--

CREATE TABLE public.favorite (
    user_id bigint NOT NULL,
    entity_id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.favorite OWNER TO a1;

--
-- TOC entry 249 (class 1259 OID 33423)
-- Name: film; Type: TABLE; Schema: public; Owner: a1
--

CREATE TABLE public.film (
    id bigint NOT NULL,
    release_year smallint,
    release_date date,
    runtime_min integer,
    original_language_id smallint,
    age_rating character varying(20),
    sort_title character varying(255),
    extra_metadata jsonb DEFAULT '{}'::jsonb NOT NULL
);


ALTER TABLE public.film OWNER TO a1;

--
-- TOC entry 250 (class 1259 OID 33429)
-- Name: film_person; Type: TABLE; Schema: public; Owner: a1
--

CREATE TABLE public.film_person (
    film_id bigint NOT NULL,
    person_id bigint NOT NULL,
    role_type public.film_person_role NOT NULL,
    character_name character varying(255),
    billing_order smallint,
    is_primary boolean DEFAULT false NOT NULL,
    note text,
    confidence numeric(3,2) DEFAULT 1.00 NOT NULL,
    source_id bigint,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.film_person OWNER TO a1;

--
-- TOC entry 282 (class 1259 OID 34568)
-- Name: film_studio; Type: TABLE; Schema: public; Owner: a1
--

CREATE TABLE public.film_studio (
    film_id bigint NOT NULL,
    studio_id bigint NOT NULL,
    role public.studio_role DEFAULT 'production'::public.studio_role NOT NULL,
    is_primary boolean DEFAULT false NOT NULL,
    note text,
    source_id bigint,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.film_studio OWNER TO a1;

--
-- TOC entry 251 (class 1259 OID 33437)
-- Name: language; Type: TABLE; Schema: public; Owner: a1
--

CREATE TABLE public.language (
    id smallint NOT NULL,
    code character varying(10) NOT NULL,
    locale_code character varying(20),
    english_name character varying(100) NOT NULL,
    native_name character varying(100) NOT NULL,
    default_search_config regconfig DEFAULT 'simple'::regconfig NOT NULL,
    is_active boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.language OWNER TO a1;

--
-- TOC entry 252 (class 1259 OID 33443)
-- Name: language_id_seq; Type: SEQUENCE; Schema: public; Owner: a1
--

ALTER TABLE public.language ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.language_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 253 (class 1259 OID 33444)
-- Name: media_asset; Type: TABLE; Schema: public; Owner: a1
--

CREATE TABLE public.media_asset (
    id bigint NOT NULL,
    url text NOT NULL,
    source_kind public.media_source_kind DEFAULT 'external'::public.media_source_kind NOT NULL,
    external_id character varying(255),
    width integer,
    height integer,
    format character varying(10),
    mime_type character varying(50),
    file_size_bytes bigint,
    dominant_color character varying(7),
    alt_text text,
    caption text,
    attribution text,
    license character varying(50) DEFAULT 'unknown'::character varying,
    uploaded_by_user_id bigint,
    extra_metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT media_asset_dominant_color_hex CHECK (((dominant_color IS NULL) OR ((dominant_color)::text ~ '^#[0-9A-Fa-f]{6}$'::text))),
    CONSTRAINT media_asset_height_positive CHECK (((height IS NULL) OR (height > 0))),
    CONSTRAINT media_asset_width_positive CHECK (((width IS NULL) OR (width > 0)))
);


ALTER TABLE public.media_asset OWNER TO a1;

--
-- TOC entry 254 (class 1259 OID 33457)
-- Name: media_asset_id_seq; Type: SEQUENCE; Schema: public; Owner: a1
--

ALTER TABLE public.media_asset ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.media_asset_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 255 (class 1259 OID 33458)
-- Name: search_history; Type: TABLE; Schema: public; Owner: a1
--

CREATE TABLE public.search_history (
    id bigint NOT NULL,
    user_id bigint,
    session_id character varying(64),
    query_text text NOT NULL,
    normalized_query text,
    searched_at timestamp with time zone DEFAULT now() NOT NULL,
    results_count integer DEFAULT 0 NOT NULL,
    clicked_entity_id bigint,
    click_position smallint,
    language_id smallint,
    search_type public.search_type DEFAULT 'fulltext'::public.search_type NOT NULL,
    filters jsonb DEFAULT '{}'::jsonb NOT NULL,
    duration_ms integer,
    ip_address inet,
    extra_metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
    CONSTRAINT search_history_duration_nonneg CHECK (((duration_ms IS NULL) OR (duration_ms >= 0))),
    CONSTRAINT search_history_query_not_empty CHECK ((length(TRIM(BOTH FROM query_text)) > 0)),
    CONSTRAINT search_history_results_nonneg CHECK ((results_count >= 0))
);


ALTER TABLE public.search_history OWNER TO a1;

--
-- TOC entry 256 (class 1259 OID 33471)
-- Name: search_history_id_seq; Type: SEQUENCE; Schema: public; Owner: a1
--

ALTER TABLE public.search_history ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.search_history_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 257 (class 1259 OID 33472)
-- Name: source; Type: TABLE; Schema: public; Owner: a1
--

CREATE TABLE public.source (
    id bigint NOT NULL,
    source_type character varying(30) NOT NULL,
    title text NOT NULL,
    authors_text text,
    publisher text,
    publication_date date,
    language_id smallint,
    url text,
    access_date date,
    doi character varying(255),
    isbn character varying(32),
    citation_text text,
    extra_metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.source OWNER TO a1;

--
-- TOC entry 258 (class 1259 OID 33479)
-- Name: source_id_seq; Type: SEQUENCE; Schema: public; Owner: a1
--

ALTER TABLE public.source ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.source_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 280 (class 1259 OID 34530)
-- Name: studio; Type: TABLE; Schema: public; Owner: a1
--

CREATE TABLE public.studio (
    id bigint NOT NULL,
    code character varying(64) NOT NULL,
    country_code character varying(8),
    founded_year smallint,
    closed_year smallint,
    is_active boolean DEFAULT true NOT NULL,
    parent_studio_id bigint,
    headquarters character varying(255),
    official_url text,
    extra_metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT studio_year_order CHECK (((closed_year IS NULL) OR (founded_year IS NULL) OR (closed_year >= founded_year))),
    CONSTRAINT studio_year_reasonable CHECK ((((founded_year IS NULL) OR ((founded_year >= 1880) AND (founded_year <= 2100))) AND ((closed_year IS NULL) OR ((closed_year >= 1880) AND (closed_year <= 2100)))))
);


ALTER TABLE public.studio OWNER TO a1;

--
-- TOC entry 279 (class 1259 OID 34529)
-- Name: studio_id_seq; Type: SEQUENCE; Schema: public; Owner: a1
--

ALTER TABLE public.studio ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.studio_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 281 (class 1259 OID 34550)
-- Name: studio_translation; Type: TABLE; Schema: public; Owner: a1
--

CREATE TABLE public.studio_translation (
    studio_id bigint NOT NULL,
    language_id smallint NOT NULL,
    name character varying(255) NOT NULL,
    description text,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.studio_translation OWNER TO a1;

--
-- TOC entry 259 (class 1259 OID 33480)
-- Name: taxonomy_term; Type: TABLE; Schema: public; Owner: a1
--

CREATE TABLE public.taxonomy_term (
    id bigint NOT NULL,
    term_type public.taxonomy_type NOT NULL,
    code character varying(64),
    iso_code character varying(8),
    parent_term_id bigint,
    is_system boolean DEFAULT true NOT NULL,
    sort_order integer DEFAULT 0 NOT NULL,
    extra_metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.taxonomy_term OWNER TO a1;

--
-- TOC entry 260 (class 1259 OID 33489)
-- Name: taxonomy_term_id_seq; Type: SEQUENCE; Schema: public; Owner: a1
--

ALTER TABLE public.taxonomy_term ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.taxonomy_term_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 261 (class 1259 OID 33490)
-- Name: taxonomy_term_translation; Type: TABLE; Schema: public; Owner: a1
--

CREATE TABLE public.taxonomy_term_translation (
    term_id bigint NOT NULL,
    language_id smallint NOT NULL,
    slug character varying(255),
    name character varying(255) NOT NULL,
    description text
);


ALTER TABLE public.taxonomy_term_translation OWNER TO a1;

--
-- TOC entry 288 (class 1259 OID 34681)
-- Name: user_note; Type: TABLE; Schema: public; Owner: a1
--

CREATE TABLE public.user_note (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    entity_id bigint NOT NULL,
    title character varying(255),
    body text NOT NULL,
    is_pinned boolean DEFAULT false NOT NULL,
    color_label character varying(7),
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT user_note_body_not_empty CHECK ((length(TRIM(BOTH FROM body)) > 0)),
    CONSTRAINT user_note_color_hex CHECK (((color_label IS NULL) OR ((color_label)::text ~ '^#[0-9A-Fa-f]{6}$'::text)))
);


ALTER TABLE public.user_note OWNER TO a1;

--
-- TOC entry 287 (class 1259 OID 34680)
-- Name: user_note_id_seq; Type: SEQUENCE; Schema: public; Owner: a1
--

ALTER TABLE public.user_note ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_note_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 285 (class 1259 OID 34636)
-- Name: user_rating; Type: TABLE; Schema: public; Owner: a1
--

CREATE TABLE public.user_rating (
    user_id bigint NOT NULL,
    entity_id bigint NOT NULL,
    rating smallint NOT NULL,
    would_recommend boolean,
    rated_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT user_rating_range CHECK (((rating >= 1) AND (rating <= 10)))
);


ALTER TABLE public.user_rating OWNER TO a1;

--
-- TOC entry 286 (class 1259 OID 34656)
-- Name: user_watchlist; Type: TABLE; Schema: public; Owner: a1
--

CREATE TABLE public.user_watchlist (
    user_id bigint NOT NULL,
    entity_id bigint NOT NULL,
    status public.watchlist_status DEFAULT 'want_to_watch'::public.watchlist_status NOT NULL,
    added_at timestamp with time zone DEFAULT now() NOT NULL,
    started_watching_at timestamp with time zone,
    watched_at timestamp with time zone,
    dropped_at timestamp with time zone,
    rewatched_count smallint DEFAULT 0 NOT NULL,
    note text,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT user_watchlist_rewatched_nonneg CHECK ((rewatched_count >= 0))
);


ALTER TABLE public.user_watchlist OWNER TO a1;

--
-- TOC entry 262 (class 1259 OID 33495)
-- Name: v_active_clusters; Type: VIEW; Schema: public; Owner: a1
--

CREATE VIEW public.v_active_clusters AS
SELECT
    NULL::bigint AS id,
    NULL::character varying(64) AS code,
    NULL::public.cluster_kind AS kind,
    NULL::smallint AS period_start,
    NULL::smallint AS period_end,
    NULL::character varying(8) AS country_code,
    NULL::boolean AS is_active,
    NULL::bigint AS members_count,
    NULL::bigint AS core_members_count,
    NULL::timestamp with time zone AS created_at;


ALTER VIEW public.v_active_clusters OWNER TO a1;

--
-- TOC entry 263 (class 1259 OID 33499)
-- Name: v_director_lineage; Type: VIEW; Schema: public; Owner: a1
--

CREATE VIEW public.v_director_lineage AS
 SELECT p.id AS director_id,
    s.out_degree,
    s.in_degree,
    s.top_mentors,
    s.top_followers,
    s.aspects_received,
    s.aspects_given,
    s.earliest_influence_year,
    s.latest_influence_year,
    ARRAY( SELECT cm.cluster_id
           FROM public.director_cluster_member cm
          WHERE (cm.director_id = p.id)) AS cluster_ids
   FROM (public.person p
     LEFT JOIN public.director_influence_stats s ON ((s.director_id = p.id)))
  WHERE (p.is_director = true);


ALTER VIEW public.v_director_lineage OWNER TO a1;

--
-- TOC entry 289 (class 1259 OID 34713)
-- Name: v_entity_awards_summary; Type: VIEW; Schema: public; Owner: a1
--

CREATE VIEW public.v_entity_awards_summary AS
 SELECT n.entity_id,
    count(*) FILTER (WHERE (n.status = 'won'::public.nomination_status)) AS wins_count,
    count(*) FILTER (WHERE (n.status = 'nominated'::public.nomination_status)) AS nominations_count,
    array_agg(DISTINCT a.code) FILTER (WHERE (n.status = 'won'::public.nomination_status)) AS won_awards,
    max(c.year) AS last_award_year
   FROM ((public.award_nomination n
     JOIN public.award_ceremony c ON ((c.id = n.ceremony_id)))
     JOIN public.award a ON ((a.id = c.award_id)))
  GROUP BY n.entity_id;


ALTER VIEW public.v_entity_awards_summary OWNER TO a1;

--
-- TOC entry 264 (class 1259 OID 33504)
-- Name: view_history; Type: TABLE; Schema: public; Owner: a1
--

CREATE TABLE public.view_history (
    id bigint NOT NULL,
    user_id bigint,
    session_id character varying(64),
    entity_id bigint NOT NULL,
    viewed_at timestamp with time zone DEFAULT now() NOT NULL,
    duration_seconds integer,
    referrer_kind public.referrer_kind DEFAULT 'unknown'::public.referrer_kind NOT NULL,
    referrer_entity_id bigint,
    device_kind public.device_kind DEFAULT 'unknown'::public.device_kind NOT NULL,
    ip_address inet,
    user_agent text,
    language_id smallint,
    extra_metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
    CONSTRAINT view_history_duration_nonneg CHECK (((duration_seconds IS NULL) OR (duration_seconds >= 0))),
    CONSTRAINT view_history_user_or_session CHECK (((user_id IS NOT NULL) OR (session_id IS NOT NULL)))
);


ALTER TABLE public.view_history OWNER TO a1;

--
-- TOC entry 265 (class 1259 OID 33515)
-- Name: v_popular_entities; Type: VIEW; Schema: public; Owner: a1
--

CREATE VIEW public.v_popular_entities AS
 SELECT vh.entity_id,
    e.entity_type,
    count(*) AS total_views,
    count(DISTINCT vh.user_id) AS unique_users,
    count(DISTINCT vh.session_id) AS unique_sessions,
    (avg(vh.duration_seconds))::integer AS avg_duration_seconds,
    max(vh.viewed_at) AS last_viewed_at
   FROM (public.view_history vh
     JOIN public.entity e ON ((e.id = vh.entity_id)))
  WHERE (vh.viewed_at > (now() - '30 days'::interval))
  GROUP BY vh.entity_id, e.entity_type;


ALTER VIEW public.v_popular_entities OWNER TO a1;

--
-- TOC entry 291 (class 1259 OID 34723)
-- Name: v_studio_filmography; Type: VIEW; Schema: public; Owner: a1
--

CREATE VIEW public.v_studio_filmography AS
 SELECT fs.studio_id,
    count(*) AS films_count,
    count(*) FILTER (WHERE (fs.role = 'production'::public.studio_role)) AS produced_count,
    count(*) FILTER (WHERE (fs.role = 'distribution'::public.studio_role)) AS distributed_count,
    min(f.release_year) AS earliest_film_year,
    max(f.release_year) AS latest_film_year
   FROM (public.film_studio fs
     JOIN public.film f ON ((f.id = fs.film_id)))
  GROUP BY fs.studio_id;


ALTER VIEW public.v_studio_filmography OWNER TO a1;

--
-- TOC entry 290 (class 1259 OID 34718)
-- Name: v_user_film_state; Type: VIEW; Schema: public; Owner: a1
--

CREATE VIEW public.v_user_film_state AS
 SELECT u.id AS user_id,
    e.id AS entity_id,
    r.rating,
    r.would_recommend,
    w.status AS watchlist_status,
    w.watched_at,
    w.rewatched_count,
    (f.user_id IS NOT NULL) AS is_favorite,
    ( SELECT count(*) AS count
           FROM public.user_note n
          WHERE ((n.user_id = u.id) AND (n.entity_id = e.id))) AS notes_count
   FROM ((((public.app_user u
     CROSS JOIN public.entity e)
     LEFT JOIN public.user_rating r ON (((r.user_id = u.id) AND (r.entity_id = e.id))))
     LEFT JOIN public.user_watchlist w ON (((w.user_id = u.id) AND (w.entity_id = e.id))))
     LEFT JOIN public.favorite f ON (((f.user_id = u.id) AND (f.entity_id = e.id))))
  WHERE ((r.user_id IS NOT NULL) OR (w.user_id IS NOT NULL) OR (f.user_id IS NOT NULL));


ALTER VIEW public.v_user_film_state OWNER TO a1;

--
-- TOC entry 266 (class 1259 OID 33520)
-- Name: v_user_recent_interests; Type: VIEW; Schema: public; Owner: a1
--

CREATE VIEW public.v_user_recent_interests AS
 SELECT vh.user_id,
    vh.entity_id,
    e.entity_type,
    count(*) AS view_count,
    max(vh.viewed_at) AS last_viewed_at,
    (avg(vh.duration_seconds))::integer AS avg_duration_seconds,
    sum(vh.duration_seconds) AS total_duration_seconds,
    count(DISTINCT vh.session_id) AS distinct_sessions
   FROM (public.view_history vh
     JOIN public.entity e ON ((e.id = vh.entity_id)))
  WHERE ((vh.user_id IS NOT NULL) AND (vh.viewed_at > (now() - '90 days'::interval)) AND ((vh.duration_seconds IS NULL) OR (vh.duration_seconds >= 5)))
  GROUP BY vh.user_id, vh.entity_id, e.entity_type;


ALTER VIEW public.v_user_recent_interests OWNER TO a1;

--
-- TOC entry 267 (class 1259 OID 33525)
-- Name: v_zero_result_searches; Type: VIEW; Schema: public; Owner: a1
--

CREATE VIEW public.v_zero_result_searches AS
 SELECT normalized_query,
    count(*) AS attempts_count,
    count(DISTINCT user_id) AS unique_users,
    max(searched_at) AS last_attempt_at
   FROM public.search_history
  WHERE ((results_count = 0) AND (searched_at > (now() - '30 days'::interval)) AND (normalized_query IS NOT NULL))
  GROUP BY normalized_query
 HAVING (count(*) >= 2)
  ORDER BY (count(*)) DESC;


ALTER VIEW public.v_zero_result_searches OWNER TO a1;

--
-- TOC entry 268 (class 1259 OID 33529)
-- Name: view_history_id_seq; Type: SEQUENCE; Schema: public; Owner: a1
--

ALTER TABLE public.view_history ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.view_history_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 4301 (class 2606 OID 33531)
-- Name: app_role app_role_code_key; Type: CONSTRAINT; Schema: public; Owner: a1
--

ALTER TABLE ONLY public.app_role
    ADD CONSTRAINT app_role_code_key UNIQUE (code);


--
-- TOC entry 4303 (class 2606 OID 33533)
-- Name: app_role app_role_pkey; Type: CONSTRAINT; Schema: public; Owner: a1
--

ALTER TABLE ONLY public.app_role
    ADD CONSTRAINT app_role_pkey PRIMARY KEY (id);


--
-- TOC entry 4305 (class 2606 OID 33535)
-- Name: app_user app_user_email_key; Type: CONSTRAINT; Schema: public; Owner: a1
--

ALTER TABLE ONLY public.app_user
    ADD CONSTRAINT app_user_email_key UNIQUE (email);


--
-- TOC entry 4307 (class 2606 OID 33537)
-- Name: app_user app_user_pkey; Type: CONSTRAINT; Schema: public; Owner: a1
--

ALTER TABLE ONLY public.app_user
    ADD CONSTRAINT app_user_pkey PRIMARY KEY (id);


--
-- TOC entry 4311 (class 2606 OID 33539)
-- Name: article_entity_link article_entity_link_pkey; Type: CONSTRAINT; Schema: public; Owner: a1
--

ALTER TABLE ONLY public.article_entity_link
    ADD CONSTRAINT article_entity_link_pkey PRIMARY KEY (article_id, entity_id, link_type);


--
-- TOC entry 4309 (class 2606 OID 33541)
-- Name: article article_pkey; Type: CONSTRAINT; Schema: public; Owner: a1
--

ALTER TABLE ONLY public.article
    ADD CONSTRAINT article_pkey PRIMARY KEY (id);


--
-- TOC entry 4313 (class 2606 OID 33543)
-- Name: audit_log audit_log_pkey; Type: CONSTRAINT; Schema: public; Owner: a1
--

ALTER TABLE ONLY public.audit_log
    ADD CONSTRAINT audit_log_pkey PRIMARY KEY (id);


--
-- TOC entry 4415 (class 2606 OID 34436)
-- Name: award_category award_category_award_id_code_key; Type: CONSTRAINT; Schema: public; Owner: a1
--

ALTER TABLE ONLY public.award_category
    ADD CONSTRAINT award_category_award_id_code_key UNIQUE (award_id, code);


--
-- TOC entry 4417 (class 2606 OID 34434)
-- Name: award_category award_category_pkey; Type: CONSTRAINT; Schema: public; Owner: a1
--

ALTER TABLE ONLY public.award_category
    ADD CONSTRAINT award_category_pkey PRIMARY KEY (id);


--
-- TOC entry 4419 (class 2606 OID 34449)
-- Name: award_category_translation award_category_translation_pkey; Type: CONSTRAINT; Schema: public; Owner: a1
--

ALTER TABLE ONLY public.award_category_translation
    ADD CONSTRAINT award_category_translation_pkey PRIMARY KEY (category_id, language_id);


--
-- TOC entry 4421 (class 2606 OID 34473)
-- Name: award_ceremony award_ceremony_award_id_year_edition_number_key; Type: CONSTRAINT; Schema: public; Owner: a1
--

ALTER TABLE ONLY public.award_ceremony
    ADD CONSTRAINT award_ceremony_award_id_year_edition_number_key UNIQUE (award_id, year, edition_number);


--
-- TOC entry 4423 (class 2606 OID 34471)
-- Name: award_ceremony award_ceremony_pkey; Type: CONSTRAINT; Schema: public; Owner: a1
--

ALTER TABLE ONLY public.award_ceremony
    ADD CONSTRAINT award_ceremony_pkey PRIMARY KEY (id);


--
-- TOC entry 4409 (class 2606 OID 34404)
-- Name: award award_code_key; Type: CONSTRAINT; Schema: public; Owner: a1
--

ALTER TABLE ONLY public.award
    ADD CONSTRAINT award_code_key UNIQUE (code);


--
-- TOC entry 4426 (class 2606 OID 34494)
-- Name: award_nomination award_nomination_ceremony_id_category_id_entity_id_person_i_key; Type: CONSTRAINT; Schema: public; Owner: a1
--

ALTER TABLE ONLY public.award_nomination
    ADD CONSTRAINT award_nomination_ceremony_id_category_id_entity_id_person_i_key UNIQUE (ceremony_id, category_id, entity_id, person_id);


--
-- TOC entry 4428 (class 2606 OID 34492)
-- Name: award_nomination award_nomination_pkey; Type: CONSTRAINT; Schema: public; Owner: a1
--

ALTER TABLE ONLY public.award_nomination
    ADD CONSTRAINT award_nomination_pkey PRIMARY KEY (id);


--
-- TOC entry 4411 (class 2606 OID 34402)
-- Name: award award_pkey; Type: CONSTRAINT; Schema: public; Owner: a1
--

ALTER TABLE ONLY public.award
    ADD CONSTRAINT award_pkey PRIMARY KEY (id);


--
-- TOC entry 4413 (class 2606 OID 34412)
-- Name: award_translation award_translation_pkey; Type: CONSTRAINT; Schema: public; Owner: a1
--

ALTER TABLE ONLY public.award_translation
    ADD CONSTRAINT award_translation_pkey PRIMARY KEY (award_id, language_id);


--
-- TOC entry 4318 (class 2606 OID 33545)
-- Name: cluster_influence cluster_influence_pkey; Type: CONSTRAINT; Schema: public; Owner: a1
--

ALTER TABLE ONLY public.cluster_influence
    ADD CONSTRAINT cluster_influence_pkey PRIMARY KEY (id);


--
-- TOC entry 4320 (class 2606 OID 33547)
-- Name: cluster_influence cluster_influence_source_cluster_id_target_cluster_id_key; Type: CONSTRAINT; Schema: public; Owner: a1
--

ALTER TABLE ONLY public.cluster_influence
    ADD CONSTRAINT cluster_influence_source_cluster_id_target_cluster_id_key UNIQUE (source_cluster_id, target_cluster_id);


--
-- TOC entry 4327 (class 2606 OID 33549)
-- Name: collection_item collection_item_collection_id_position_key; Type: CONSTRAINT; Schema: public; Owner: a1
--

ALTER TABLE ONLY public.collection_item
    ADD CONSTRAINT collection_item_collection_id_position_key UNIQUE (collection_id, "position");


--
-- TOC entry 4329 (class 2606 OID 33551)
-- Name: collection_item collection_item_pkey; Type: CONSTRAINT; Schema: public; Owner: a1
--

ALTER TABLE ONLY public.collection_item
    ADD CONSTRAINT collection_item_pkey PRIMARY KEY (collection_id, entity_id);


--
-- TOC entry 4325 (class 2606 OID 33553)
-- Name: collection collection_pkey; Type: CONSTRAINT; Schema: public; Owner: a1
--

ALTER TABLE ONLY public.collection
    ADD CONSTRAINT collection_pkey PRIMARY KEY (id);


--
-- TOC entry 4331 (class 2606 OID 33555)
-- Name: director_cluster director_cluster_code_key; Type: CONSTRAINT; Schema: public; Owner: a1
--

ALTER TABLE ONLY public.director_cluster
    ADD CONSTRAINT director_cluster_code_key UNIQUE (code);


--
-- TOC entry 4335 (class 2606 OID 33557)
-- Name: director_cluster_member director_cluster_member_pkey; Type: CONSTRAINT; Schema: public; Owner: a1
--

ALTER TABLE ONLY public.director_cluster_member
    ADD CONSTRAINT director_cluster_member_pkey PRIMARY KEY (cluster_id, director_id);


--
-- TOC entry 4333 (class 2606 OID 33559)
-- Name: director_cluster director_cluster_pkey; Type: CONSTRAINT; Schema: public; Owner: a1
--

ALTER TABLE ONLY public.director_cluster
    ADD CONSTRAINT director_cluster_pkey PRIMARY KEY (id);


--
-- TOC entry 4339 (class 2606 OID 33561)
-- Name: director_cluster_translation director_cluster_translation_pkey; Type: CONSTRAINT; Schema: public; Owner: a1
--

ALTER TABLE ONLY public.director_cluster_translation
    ADD CONSTRAINT director_cluster_translation_pkey PRIMARY KEY (cluster_id, language_id);


--
-- TOC entry 4341 (class 2606 OID 33563)
-- Name: director_influence director_influence_pkey; Type: CONSTRAINT; Schema: public; Owner: a1
--

ALTER TABLE ONLY public.director_influence
    ADD CONSTRAINT director_influence_pkey PRIMARY KEY (id);


--
-- TOC entry 4343 (class 2606 OID 33565)
-- Name: director_influence director_influence_source_director_id_target_director_id_key; Type: CONSTRAINT; Schema: public; Owner: a1
--

ALTER TABLE ONLY public.director_influence
    ADD CONSTRAINT director_influence_source_director_id_target_director_id_key UNIQUE (source_director_id, target_director_id);


--
-- TOC entry 4350 (class 2606 OID 33567)
-- Name: director_influence_source director_influence_source_pkey; Type: CONSTRAINT; Schema: public; Owner: a1
--

ALTER TABLE ONLY public.director_influence_source
    ADD CONSTRAINT director_influence_source_pkey PRIMARY KEY (influence_id, source_id);


--
-- TOC entry 4356 (class 2606 OID 33569)
-- Name: entity_media entity_media_pkey; Type: CONSTRAINT; Schema: public; Owner: a1
--

ALTER TABLE ONLY public.entity_media
    ADD CONSTRAINT entity_media_pkey PRIMARY KEY (entity_id, media_id, role);


--
-- TOC entry 4354 (class 2606 OID 33571)
-- Name: entity entity_pkey; Type: CONSTRAINT; Schema: public; Owner: a1
--

ALTER TABLE ONLY public.entity
    ADD CONSTRAINT entity_pkey PRIMARY KEY (id);


--
-- TOC entry 4443 (class 2606 OID 34610)
-- Name: entity_relation entity_relation_pkey; Type: CONSTRAINT; Schema: public; Owner: a1
--

ALTER TABLE ONLY public.entity_relation
    ADD CONSTRAINT entity_relation_pkey PRIMARY KEY (id);


--
-- TOC entry 4445 (class 2606 OID 34612)
-- Name: entity_relation entity_relation_source_entity_id_target_entity_id_relation__key; Type: CONSTRAINT; Schema: public; Owner: a1
--

ALTER TABLE ONLY public.entity_relation
    ADD CONSTRAINT entity_relation_source_entity_id_target_entity_id_relation__key UNIQUE (source_entity_id, target_entity_id, relation_kind);


--
-- TOC entry 4362 (class 2606 OID 33573)
-- Name: entity_taxonomy entity_taxonomy_pkey; Type: CONSTRAINT; Schema: public; Owner: a1
--

ALTER TABLE ONLY public.entity_taxonomy
    ADD CONSTRAINT entity_taxonomy_pkey PRIMARY KEY (entity_id, term_id);


--
-- TOC entry 4364 (class 2606 OID 33575)
-- Name: entity_translation entity_translation_language_id_slug_key; Type: CONSTRAINT; Schema: public; Owner: a1
--

ALTER TABLE ONLY public.entity_translation
    ADD CONSTRAINT entity_translation_language_id_slug_key UNIQUE (language_id, slug);


--
-- TOC entry 4366 (class 2606 OID 33577)
-- Name: entity_translation entity_translation_pkey; Type: CONSTRAINT; Schema: public; Owner: a1
--

ALTER TABLE ONLY public.entity_translation
    ADD CONSTRAINT entity_translation_pkey PRIMARY KEY (entity_id, language_id);


--
-- TOC entry 4370 (class 2606 OID 33579)
-- Name: entity_version entity_version_entity_id_version_no_key; Type: CONSTRAINT; Schema: public; Owner: a1
--

ALTER TABLE ONLY public.entity_version
    ADD CONSTRAINT entity_version_entity_id_version_no_key UNIQUE (entity_id, version_no);


--
-- TOC entry 4372 (class 2606 OID 33581)
-- Name: entity_version entity_version_pkey; Type: CONSTRAINT; Schema: public; Owner: a1
--

ALTER TABLE ONLY public.entity_version
    ADD CONSTRAINT entity_version_pkey PRIMARY KEY (id);


--
-- TOC entry 4374 (class 2606 OID 33583)
-- Name: favorite favorite_pkey; Type: CONSTRAINT; Schema: public; Owner: a1
--

ALTER TABLE ONLY public.favorite
    ADD CONSTRAINT favorite_pkey PRIMARY KEY (user_id, entity_id);


--
-- TOC entry 4379 (class 2606 OID 33585)
-- Name: film_person film_person_pkey; Type: CONSTRAINT; Schema: public; Owner: a1
--

ALTER TABLE ONLY public.film_person
    ADD CONSTRAINT film_person_pkey PRIMARY KEY (film_id, person_id, role_type);


--
-- TOC entry 4377 (class 2606 OID 33587)
-- Name: film film_pkey; Type: CONSTRAINT; Schema: public; Owner: a1
--

ALTER TABLE ONLY public.film
    ADD CONSTRAINT film_pkey PRIMARY KEY (id);


--
-- TOC entry 4440 (class 2606 OID 34577)
-- Name: film_studio film_studio_pkey; Type: CONSTRAINT; Schema: public; Owner: a1
--

ALTER TABLE ONLY public.film_studio
    ADD CONSTRAINT film_studio_pkey PRIMARY KEY (film_id, studio_id, role);


--
-- TOC entry 4381 (class 2606 OID 33589)
-- Name: language language_code_key; Type: CONSTRAINT; Schema: public; Owner: a1
--

ALTER TABLE ONLY public.language
    ADD CONSTRAINT language_code_key UNIQUE (code);


--
-- TOC entry 4383 (class 2606 OID 33591)
-- Name: language language_locale_code_key; Type: CONSTRAINT; Schema: public; Owner: a1
--

ALTER TABLE ONLY public.language
    ADD CONSTRAINT language_locale_code_key UNIQUE (locale_code);


--
-- TOC entry 4385 (class 2606 OID 33593)
-- Name: language language_pkey; Type: CONSTRAINT; Schema: public; Owner: a1
--

ALTER TABLE ONLY public.language
    ADD CONSTRAINT language_pkey PRIMARY KEY (id);


--
-- TOC entry 4388 (class 2606 OID 33595)
-- Name: media_asset media_asset_pkey; Type: CONSTRAINT; Schema: public; Owner: a1
--

ALTER TABLE ONLY public.media_asset
    ADD CONSTRAINT media_asset_pkey PRIMARY KEY (id);


--
-- TOC entry 4352 (class 2606 OID 33597)
-- Name: person person_pkey; Type: CONSTRAINT; Schema: public; Owner: a1
--

ALTER TABLE ONLY public.person
    ADD CONSTRAINT person_pkey PRIMARY KEY (id);


--
-- TOC entry 4394 (class 2606 OID 33599)
-- Name: search_history search_history_pkey; Type: CONSTRAINT; Schema: public; Owner: a1
--

ALTER TABLE ONLY public.search_history
    ADD CONSTRAINT search_history_pkey PRIMARY KEY (id);


--
-- TOC entry 4396 (class 2606 OID 33601)
-- Name: source source_pkey; Type: CONSTRAINT; Schema: public; Owner: a1
--

ALTER TABLE ONLY public.source
    ADD CONSTRAINT source_pkey PRIMARY KEY (id);


--
-- TOC entry 4434 (class 2606 OID 34544)
-- Name: studio studio_code_key; Type: CONSTRAINT; Schema: public; Owner: a1
--

ALTER TABLE ONLY public.studio
    ADD CONSTRAINT studio_code_key UNIQUE (code);


--
-- TOC entry 4436 (class 2606 OID 34542)
-- Name: studio studio_pkey; Type: CONSTRAINT; Schema: public; Owner: a1
--

ALTER TABLE ONLY public.studio
    ADD CONSTRAINT studio_pkey PRIMARY KEY (id);


--
-- TOC entry 4438 (class 2606 OID 34557)
-- Name: studio_translation studio_translation_pkey; Type: CONSTRAINT; Schema: public; Owner: a1
--

ALTER TABLE ONLY public.studio_translation
    ADD CONSTRAINT studio_translation_pkey PRIMARY KEY (studio_id, language_id);


--
-- TOC entry 4398 (class 2606 OID 33603)
-- Name: taxonomy_term taxonomy_term_pkey; Type: CONSTRAINT; Schema: public; Owner: a1
--

ALTER TABLE ONLY public.taxonomy_term
    ADD CONSTRAINT taxonomy_term_pkey PRIMARY KEY (id);


--
-- TOC entry 4400 (class 2606 OID 33605)
-- Name: taxonomy_term_translation taxonomy_term_translation_pkey; Type: CONSTRAINT; Schema: public; Owner: a1
--

ALTER TABLE ONLY public.taxonomy_term_translation
    ADD CONSTRAINT taxonomy_term_translation_pkey PRIMARY KEY (term_id, language_id);


--
-- TOC entry 4461 (class 2606 OID 34692)
-- Name: user_note user_note_pkey; Type: CONSTRAINT; Schema: public; Owner: a1
--

ALTER TABLE ONLY public.user_note
    ADD CONSTRAINT user_note_pkey PRIMARY KEY (id);


--
-- TOC entry 4452 (class 2606 OID 34643)
-- Name: user_rating user_rating_pkey; Type: CONSTRAINT; Schema: public; Owner: a1
--

ALTER TABLE ONLY public.user_rating
    ADD CONSTRAINT user_rating_pkey PRIMARY KEY (user_id, entity_id);


--
-- TOC entry 4456 (class 2606 OID 34667)
-- Name: user_watchlist user_watchlist_pkey; Type: CONSTRAINT; Schema: public; Owner: a1
--

ALTER TABLE ONLY public.user_watchlist
    ADD CONSTRAINT user_watchlist_pkey PRIMARY KEY (user_id, entity_id);


--
-- TOC entry 4407 (class 2606 OID 33607)
-- Name: view_history view_history_pkey; Type: CONSTRAINT; Schema: public; Owner: a1
--

ALTER TABLE ONLY public.view_history
    ADD CONSTRAINT view_history_pkey PRIMARY KEY (id);


--
-- TOC entry 4314 (class 1259 OID 33608)
-- Name: idx_audit_log_created; Type: INDEX; Schema: public; Owner: a1
--

CREATE INDEX idx_audit_log_created ON public.audit_log USING btree (created_at DESC);


--
-- TOC entry 4315 (class 1259 OID 33609)
-- Name: idx_audit_log_entity; Type: INDEX; Schema: public; Owner: a1
--

CREATE INDEX idx_audit_log_entity ON public.audit_log USING btree (entity_id, created_at DESC);


--
-- TOC entry 4316 (class 1259 OID 33610)
-- Name: idx_audit_log_user; Type: INDEX; Schema: public; Owner: a1
--

CREATE INDEX idx_audit_log_user ON public.audit_log USING btree (user_id, created_at DESC);


--
-- TOC entry 4424 (class 1259 OID 34479)
-- Name: idx_award_ceremony_year; Type: INDEX; Schema: public; Owner: a1
--

CREATE INDEX idx_award_ceremony_year ON public.award_ceremony USING btree (year DESC);


--
-- TOC entry 4429 (class 1259 OID 34525)
-- Name: idx_award_nomination_entity; Type: INDEX; Schema: public; Owner: a1
--

CREATE INDEX idx_award_nomination_entity ON public.award_nomination USING btree (entity_id);


--
-- TOC entry 4430 (class 1259 OID 34526)
-- Name: idx_award_nomination_person; Type: INDEX; Schema: public; Owner: a1
--

CREATE INDEX idx_award_nomination_person ON public.award_nomination USING btree (person_id) WHERE (person_id IS NOT NULL);


--
-- TOC entry 4431 (class 1259 OID 34527)
-- Name: idx_award_nomination_status; Type: INDEX; Schema: public; Owner: a1
--

CREATE INDEX idx_award_nomination_status ON public.award_nomination USING btree (status);


--
-- TOC entry 4432 (class 1259 OID 34528)
-- Name: idx_award_nomination_won; Type: INDEX; Schema: public; Owner: a1
--

CREATE INDEX idx_award_nomination_won ON public.award_nomination USING btree (category_id, ceremony_id) WHERE (status = 'won'::public.nomination_status);


--
-- TOC entry 4321 (class 1259 OID 33611)
-- Name: idx_cluster_influence_aspects; Type: INDEX; Schema: public; Owner: a1
--

CREATE INDEX idx_cluster_influence_aspects ON public.cluster_influence USING gin (influence_aspects);


--
-- TOC entry 4322 (class 1259 OID 33612)
-- Name: idx_cluster_influence_source; Type: INDEX; Schema: public; Owner: a1
--

CREATE INDEX idx_cluster_influence_source ON public.cluster_influence USING btree (source_cluster_id, weight DESC);


--
-- TOC entry 4323 (class 1259 OID 33613)
-- Name: idx_cluster_influence_target; Type: INDEX; Schema: public; Owner: a1
--

CREATE INDEX idx_cluster_influence_target ON public.cluster_influence USING btree (target_cluster_id, weight DESC);


--
-- TOC entry 4336 (class 1259 OID 33614)
-- Name: idx_cluster_member_core; Type: INDEX; Schema: public; Owner: a1
--

CREATE INDEX idx_cluster_member_core ON public.director_cluster_member USING btree (cluster_id, is_core) WHERE (is_core = true);


--
-- TOC entry 4337 (class 1259 OID 33615)
-- Name: idx_cluster_member_director; Type: INDEX; Schema: public; Owner: a1
--

CREATE INDEX idx_cluster_member_director ON public.director_cluster_member USING btree (director_id);


--
-- TOC entry 4344 (class 1259 OID 33616)
-- Name: idx_director_influence_aspects; Type: INDEX; Schema: public; Owner: a1
--

CREATE INDEX idx_director_influence_aspects ON public.director_influence USING gin (influence_aspects);


--
-- TOC entry 4345 (class 1259 OID 33617)
-- Name: idx_director_influence_key_film; Type: INDEX; Schema: public; Owner: a1
--

CREATE INDEX idx_director_influence_key_film ON public.director_influence USING btree (key_film_id) WHERE (key_film_id IS NOT NULL);


--
-- TOC entry 4346 (class 1259 OID 33618)
-- Name: idx_director_influence_period; Type: INDEX; Schema: public; Owner: a1
--

CREATE INDEX idx_director_influence_period ON public.director_influence USING btree (influence_period_start, influence_period_end) WHERE (influence_period_start IS NOT NULL);


--
-- TOC entry 4347 (class 1259 OID 33619)
-- Name: idx_director_influence_source; Type: INDEX; Schema: public; Owner: a1
--

CREATE INDEX idx_director_influence_source ON public.director_influence USING btree (source_director_id, weight DESC);


--
-- TOC entry 4348 (class 1259 OID 33620)
-- Name: idx_director_influence_target; Type: INDEX; Schema: public; Owner: a1
--

CREATE INDEX idx_director_influence_target ON public.director_influence USING btree (target_director_id, weight DESC);


--
-- TOC entry 4357 (class 1259 OID 33624)
-- Name: idx_entity_media_entity_role_pos; Type: INDEX; Schema: public; Owner: a1
--

CREATE INDEX idx_entity_media_entity_role_pos ON public.entity_media USING btree (entity_id, role, "position");


--
-- TOC entry 4358 (class 1259 OID 33625)
-- Name: idx_entity_media_media_id; Type: INDEX; Schema: public; Owner: a1
--

CREATE INDEX idx_entity_media_media_id ON public.entity_media USING btree (media_id);


--
-- TOC entry 4359 (class 1259 OID 33626)
-- Name: idx_entity_media_primary_per_role; Type: INDEX; Schema: public; Owner: a1
--

CREATE UNIQUE INDEX idx_entity_media_primary_per_role ON public.entity_media USING btree (entity_id, role) WHERE (is_primary = true);


--
-- TOC entry 4360 (class 1259 OID 33627)
-- Name: idx_entity_media_role; Type: INDEX; Schema: public; Owner: a1
--

CREATE INDEX idx_entity_media_role ON public.entity_media USING btree (role);


--
-- TOC entry 4446 (class 1259 OID 34635)
-- Name: idx_entity_relation_editorial; Type: INDEX; Schema: public; Owner: a1
--

CREATE INDEX idx_entity_relation_editorial ON public.entity_relation USING btree (source_entity_id, relation_kind) WHERE (is_editorial = true);


--
-- TOC entry 4447 (class 1259 OID 34633)
-- Name: idx_entity_relation_source; Type: INDEX; Schema: public; Owner: a1
--

CREATE INDEX idx_entity_relation_source ON public.entity_relation USING btree (source_entity_id, relation_kind);


--
-- TOC entry 4448 (class 1259 OID 34634)
-- Name: idx_entity_relation_target; Type: INDEX; Schema: public; Owner: a1
--

CREATE INDEX idx_entity_relation_target ON public.entity_relation USING btree (target_entity_id, relation_kind);


--
-- TOC entry 4367 (class 1259 OID 33628)
-- Name: idx_entity_translation_search; Type: INDEX; Schema: public; Owner: a1
--

CREATE INDEX idx_entity_translation_search ON public.entity_translation USING gin (search_tsv);


--
-- TOC entry 4368 (class 1259 OID 33629)
-- Name: idx_entity_translation_title; Type: INDEX; Schema: public; Owner: a1
--

CREATE INDEX idx_entity_translation_title ON public.entity_translation USING gin (title public.gin_trgm_ops);


--
-- TOC entry 4375 (class 1259 OID 33630)
-- Name: idx_favorite_entity; Type: INDEX; Schema: public; Owner: a1
--

CREATE INDEX idx_favorite_entity ON public.favorite USING btree (entity_id);


--
-- TOC entry 4441 (class 1259 OID 34593)
-- Name: idx_film_studio_studio; Type: INDEX; Schema: public; Owner: a1
--

CREATE INDEX idx_film_studio_studio ON public.film_studio USING btree (studio_id);


--
-- TOC entry 4386 (class 1259 OID 33631)
-- Name: idx_media_asset_external_id_unique; Type: INDEX; Schema: public; Owner: a1
--

CREATE UNIQUE INDEX idx_media_asset_external_id_unique ON public.media_asset USING btree (external_id) WHERE (external_id IS NOT NULL);


--
-- TOC entry 4389 (class 1259 OID 33632)
-- Name: idx_search_history_query_trgm; Type: INDEX; Schema: public; Owner: a1
--

CREATE INDEX idx_search_history_query_trgm ON public.search_history USING gin (normalized_query public.gin_trgm_ops) WHERE (normalized_query IS NOT NULL);


--
-- TOC entry 4390 (class 1259 OID 33633)
-- Name: idx_search_history_recent; Type: INDEX; Schema: public; Owner: a1
--

CREATE INDEX idx_search_history_recent ON public.search_history USING btree (searched_at DESC);


--
-- TOC entry 4391 (class 1259 OID 33634)
-- Name: idx_search_history_user_time; Type: INDEX; Schema: public; Owner: a1
--

CREATE INDEX idx_search_history_user_time ON public.search_history USING btree (user_id, searched_at DESC) WHERE (user_id IS NOT NULL);


--
-- TOC entry 4392 (class 1259 OID 33635)
-- Name: idx_search_history_zero_results; Type: INDEX; Schema: public; Owner: a1
--

CREATE INDEX idx_search_history_zero_results ON public.search_history USING btree (searched_at DESC) WHERE (results_count = 0);


--
-- TOC entry 4457 (class 1259 OID 34705)
-- Name: idx_user_note_pinned; Type: INDEX; Schema: public; Owner: a1
--

CREATE INDEX idx_user_note_pinned ON public.user_note USING btree (user_id, updated_at DESC) WHERE (is_pinned = true);


--
-- TOC entry 4458 (class 1259 OID 34704)
-- Name: idx_user_note_user_entity; Type: INDEX; Schema: public; Owner: a1
--

CREATE INDEX idx_user_note_user_entity ON public.user_note USING btree (user_id, entity_id);


--
-- TOC entry 4459 (class 1259 OID 34703)
-- Name: idx_user_note_user_recent; Type: INDEX; Schema: public; Owner: a1
--

CREATE INDEX idx_user_note_user_recent ON public.user_note USING btree (user_id, updated_at DESC);


--
-- TOC entry 4449 (class 1259 OID 34654)
-- Name: idx_user_rating_entity; Type: INDEX; Schema: public; Owner: a1
--

CREATE INDEX idx_user_rating_entity ON public.user_rating USING btree (entity_id, rating DESC);


--
-- TOC entry 4450 (class 1259 OID 34655)
-- Name: idx_user_rating_user_recent; Type: INDEX; Schema: public; Owner: a1
--

CREATE INDEX idx_user_rating_user_recent ON public.user_rating USING btree (user_id, updated_at DESC);


--
-- TOC entry 4453 (class 1259 OID 34679)
-- Name: idx_user_watchlist_entity_status; Type: INDEX; Schema: public; Owner: a1
--

CREATE INDEX idx_user_watchlist_entity_status ON public.user_watchlist USING btree (entity_id, status);


--
-- TOC entry 4454 (class 1259 OID 34678)
-- Name: idx_user_watchlist_user_status; Type: INDEX; Schema: public; Owner: a1
--

CREATE INDEX idx_user_watchlist_user_status ON public.user_watchlist USING btree (user_id, status, updated_at DESC);


--
-- TOC entry 4401 (class 1259 OID 33636)
-- Name: idx_view_history_entity_time; Type: INDEX; Schema: public; Owner: a1
--

CREATE INDEX idx_view_history_entity_time ON public.view_history USING btree (entity_id, viewed_at DESC);


--
-- TOC entry 4402 (class 1259 OID 33637)
-- Name: idx_view_history_recent; Type: INDEX; Schema: public; Owner: a1
--

CREATE INDEX idx_view_history_recent ON public.view_history USING btree (viewed_at DESC);


--
-- TOC entry 4403 (class 1259 OID 33638)
-- Name: idx_view_history_referrer; Type: INDEX; Schema: public; Owner: a1
--

CREATE INDEX idx_view_history_referrer ON public.view_history USING btree (referrer_entity_id) WHERE (referrer_entity_id IS NOT NULL);


--
-- TOC entry 4404 (class 1259 OID 33639)
-- Name: idx_view_history_session; Type: INDEX; Schema: public; Owner: a1
--

CREATE INDEX idx_view_history_session ON public.view_history USING btree (session_id, viewed_at DESC) WHERE (session_id IS NOT NULL);


--
-- TOC entry 4405 (class 1259 OID 33640)
-- Name: idx_view_history_user_time; Type: INDEX; Schema: public; Owner: a1
--

CREATE INDEX idx_view_history_user_time ON public.view_history USING btree (user_id, viewed_at DESC) WHERE (user_id IS NOT NULL);


--
-- TOC entry 4711 (class 2618 OID 33498)
-- Name: v_active_clusters _RETURN; Type: RULE; Schema: public; Owner: a1
--

CREATE OR REPLACE VIEW public.v_active_clusters AS
 SELECT c.id,
    c.code,
    c.kind,
    c.period_start,
    c.period_end,
    c.country_code,
    c.is_active,
    count(cm.director_id) AS members_count,
    count(cm.director_id) FILTER (WHERE (cm.is_core = true)) AS core_members_count,
    c.created_at
   FROM (public.director_cluster c
     LEFT JOIN public.director_cluster_member cm ON ((cm.cluster_id = c.id)))
  GROUP BY c.id;


--
-- TOC entry 4556 (class 2620 OID 33642)
-- Name: entity_translation entity_translation_search_biu; Type: TRIGGER; Schema: public; Owner: a1
--

CREATE TRIGGER entity_translation_search_biu BEFORE INSERT OR UPDATE OF title, summary, description, body, search_config ON public.entity_translation FOR EACH ROW EXECUTE FUNCTION tsvector_update_trigger_column('search_tsv', 'search_config', 'title', 'summary', 'description', 'body');


--
-- TOC entry 4559 (class 2620 OID 34708)
-- Name: award_nomination trg_award_nomination_updated_at; Type: TRIGGER; Schema: public; Owner: a1
--

CREATE TRIGGER trg_award_nomination_updated_at BEFORE UPDATE ON public.award_nomination FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();


--
-- TOC entry 4558 (class 2620 OID 34706)
-- Name: award trg_award_updated_at; Type: TRIGGER; Schema: public; Owner: a1
--

CREATE TRIGGER trg_award_updated_at BEFORE UPDATE ON public.award FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();


--
-- TOC entry 4561 (class 2620 OID 34709)
-- Name: entity_relation trg_entity_relation_updated_at; Type: TRIGGER; Schema: public; Owner: a1
--

CREATE TRIGGER trg_entity_relation_updated_at BEFORE UPDATE ON public.entity_relation FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();


--
-- TOC entry 4557 (class 2620 OID 33643)
-- Name: media_asset trg_media_asset_updated_at; Type: TRIGGER; Schema: public; Owner: a1
--

CREATE TRIGGER trg_media_asset_updated_at BEFORE UPDATE ON public.media_asset FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();


--
-- TOC entry 4560 (class 2620 OID 34707)
-- Name: studio trg_studio_updated_at; Type: TRIGGER; Schema: public; Owner: a1
--

CREATE TRIGGER trg_studio_updated_at BEFORE UPDATE ON public.studio FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();


--
-- TOC entry 4564 (class 2620 OID 34712)
-- Name: user_note trg_user_note_updated_at; Type: TRIGGER; Schema: public; Owner: a1
--

CREATE TRIGGER trg_user_note_updated_at BEFORE UPDATE ON public.user_note FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();


--
-- TOC entry 4562 (class 2620 OID 34710)
-- Name: user_rating trg_user_rating_updated_at; Type: TRIGGER; Schema: public; Owner: a1
--

CREATE TRIGGER trg_user_rating_updated_at BEFORE UPDATE ON public.user_rating FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();


--
-- TOC entry 4563 (class 2620 OID 34711)
-- Name: user_watchlist trg_user_watchlist_updated_at; Type: TRIGGER; Schema: public; Owner: a1
--

CREATE TRIGGER trg_user_watchlist_updated_at BEFORE UPDATE ON public.user_watchlist FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();


--
-- TOC entry 4462 (class 2606 OID 33644)
-- Name: app_user app_user_preferred_language_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: a1
--

ALTER TABLE ONLY public.app_user
    ADD CONSTRAINT app_user_preferred_language_id_fkey FOREIGN KEY (preferred_language_id) REFERENCES public.language(id);


--
-- TOC entry 4463 (class 2606 OID 33649)
-- Name: app_user app_user_role_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: a1
--

ALTER TABLE ONLY public.app_user
    ADD CONSTRAINT app_user_role_id_fkey FOREIGN KEY (role_id) REFERENCES public.app_role(id);


--
-- TOC entry 4464 (class 2606 OID 33654)
-- Name: article article_author_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: a1
--

ALTER TABLE ONLY public.article
    ADD CONSTRAINT article_author_user_id_fkey FOREIGN KEY (author_user_id) REFERENCES public.app_user(id);


--
-- TOC entry 4467 (class 2606 OID 33659)
-- Name: article_entity_link article_entity_link_article_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: a1
--

ALTER TABLE ONLY public.article_entity_link
    ADD CONSTRAINT article_entity_link_article_id_fkey FOREIGN KEY (article_id) REFERENCES public.article(id) ON DELETE CASCADE;


--
-- TOC entry 4468 (class 2606 OID 33664)
-- Name: article_entity_link article_entity_link_entity_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: a1
--

ALTER TABLE ONLY public.article_entity_link
    ADD CONSTRAINT article_entity_link_entity_id_fkey FOREIGN KEY (entity_id) REFERENCES public.entity(id) ON DELETE CASCADE;


--
-- TOC entry 4469 (class 2606 OID 33669)
-- Name: article_entity_link article_entity_link_source_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: a1
--

ALTER TABLE ONLY public.article_entity_link
    ADD CONSTRAINT article_entity_link_source_id_fkey FOREIGN KEY (source_id) REFERENCES public.source(id);


--
-- TOC entry 4465 (class 2606 OID 33674)
-- Name: article article_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: a1
--

ALTER TABLE ONLY public.article
    ADD CONSTRAINT article_id_fkey FOREIGN KEY (id) REFERENCES public.entity(id) ON DELETE CASCADE;


--
-- TOC entry 4466 (class 2606 OID 33679)
-- Name: article article_original_source_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: a1
--

ALTER TABLE ONLY public.article
    ADD CONSTRAINT article_original_source_id_fkey FOREIGN KEY (original_source_id) REFERENCES public.source(id);


--
-- TOC entry 4470 (class 2606 OID 33684)
-- Name: audit_log audit_log_entity_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: a1
--

ALTER TABLE ONLY public.audit_log
    ADD CONSTRAINT audit_log_entity_id_fkey FOREIGN KEY (entity_id) REFERENCES public.entity(id) ON DELETE SET NULL;


--
-- TOC entry 4471 (class 2606 OID 33689)
-- Name: audit_log audit_log_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: a1
--

ALTER TABLE ONLY public.audit_log
    ADD CONSTRAINT audit_log_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.app_user(id) ON DELETE SET NULL;


--
-- TOC entry 4530 (class 2606 OID 34437)
-- Name: award_category award_category_award_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: a1
--

ALTER TABLE ONLY public.award_category
    ADD CONSTRAINT award_category_award_id_fkey FOREIGN KEY (award_id) REFERENCES public.award(id) ON DELETE CASCADE;


--
-- TOC entry 4531 (class 2606 OID 34450)
-- Name: award_category_translation award_category_translation_category_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: a1
--

ALTER TABLE ONLY public.award_category_translation
    ADD CONSTRAINT award_category_translation_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.award_category(id) ON DELETE CASCADE;


--
-- TOC entry 4532 (class 2606 OID 34455)
-- Name: award_category_translation award_category_translation_language_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: a1
--

ALTER TABLE ONLY public.award_category_translation
    ADD CONSTRAINT award_category_translation_language_id_fkey FOREIGN KEY (language_id) REFERENCES public.language(id);


--
-- TOC entry 4533 (class 2606 OID 34474)
-- Name: award_ceremony award_ceremony_award_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: a1
--

ALTER TABLE ONLY public.award_ceremony
    ADD CONSTRAINT award_ceremony_award_id_fkey FOREIGN KEY (award_id) REFERENCES public.award(id) ON DELETE CASCADE;


--
-- TOC entry 4534 (class 2606 OID 34500)
-- Name: award_nomination award_nomination_category_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: a1
--

ALTER TABLE ONLY public.award_nomination
    ADD CONSTRAINT award_nomination_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.award_category(id) ON DELETE CASCADE;


--
-- TOC entry 4535 (class 2606 OID 34495)
-- Name: award_nomination award_nomination_ceremony_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: a1
--

ALTER TABLE ONLY public.award_nomination
    ADD CONSTRAINT award_nomination_ceremony_id_fkey FOREIGN KEY (ceremony_id) REFERENCES public.award_ceremony(id) ON DELETE CASCADE;


--
-- TOC entry 4536 (class 2606 OID 34520)
-- Name: award_nomination award_nomination_created_by_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: a1
--

ALTER TABLE ONLY public.award_nomination
    ADD CONSTRAINT award_nomination_created_by_user_id_fkey FOREIGN KEY (created_by_user_id) REFERENCES public.app_user(id) ON DELETE SET NULL;


--
-- TOC entry 4537 (class 2606 OID 34505)
-- Name: award_nomination award_nomination_entity_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: a1
--

ALTER TABLE ONLY public.award_nomination
    ADD CONSTRAINT award_nomination_entity_id_fkey FOREIGN KEY (entity_id) REFERENCES public.entity(id) ON DELETE CASCADE;


--
-- TOC entry 4538 (class 2606 OID 34510)
-- Name: award_nomination award_nomination_person_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: a1
--

ALTER TABLE ONLY public.award_nomination
    ADD CONSTRAINT award_nomination_person_id_fkey FOREIGN KEY (person_id) REFERENCES public.person(id) ON DELETE SET NULL;


--
-- TOC entry 4539 (class 2606 OID 34515)
-- Name: award_nomination award_nomination_source_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: a1
--

ALTER TABLE ONLY public.award_nomination
    ADD CONSTRAINT award_nomination_source_id_fkey FOREIGN KEY (source_id) REFERENCES public.source(id) ON DELETE SET NULL;


--
-- TOC entry 4528 (class 2606 OID 34413)
-- Name: award_translation award_translation_award_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: a1
--

ALTER TABLE ONLY public.award_translation
    ADD CONSTRAINT award_translation_award_id_fkey FOREIGN KEY (award_id) REFERENCES public.award(id) ON DELETE CASCADE;


--
-- TOC entry 4529 (class 2606 OID 34418)
-- Name: award_translation award_translation_language_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: a1
--

ALTER TABLE ONLY public.award_translation
    ADD CONSTRAINT award_translation_language_id_fkey FOREIGN KEY (language_id) REFERENCES public.language(id);


--
-- TOC entry 4472 (class 2606 OID 33694)
-- Name: cluster_influence cluster_influence_created_by_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: a1
--

ALTER TABLE ONLY public.cluster_influence
    ADD CONSTRAINT cluster_influence_created_by_user_id_fkey FOREIGN KEY (created_by_user_id) REFERENCES public.app_user(id) ON DELETE SET NULL;


--
-- TOC entry 4473 (class 2606 OID 33699)
-- Name: cluster_influence cluster_influence_source_cluster_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: a1
--

ALTER TABLE ONLY public.cluster_influence
    ADD CONSTRAINT cluster_influence_source_cluster_id_fkey FOREIGN KEY (source_cluster_id) REFERENCES public.director_cluster(id) ON DELETE CASCADE;


--
-- TOC entry 4474 (class 2606 OID 33704)
-- Name: cluster_influence cluster_influence_target_cluster_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: a1
--

ALTER TABLE ONLY public.cluster_influence
    ADD CONSTRAINT cluster_influence_target_cluster_id_fkey FOREIGN KEY (target_cluster_id) REFERENCES public.director_cluster(id) ON DELETE CASCADE;


--
-- TOC entry 4475 (class 2606 OID 33709)
-- Name: collection collection_cover_entity_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: a1
--

ALTER TABLE ONLY public.collection
    ADD CONSTRAINT collection_cover_entity_id_fkey FOREIGN KEY (cover_entity_id) REFERENCES public.entity(id);


--
-- TOC entry 4476 (class 2606 OID 33714)
-- Name: collection collection_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: a1
--

ALTER TABLE ONLY public.collection
    ADD CONSTRAINT collection_id_fkey FOREIGN KEY (id) REFERENCES public.entity(id) ON DELETE CASCADE;


--
-- TOC entry 4478 (class 2606 OID 33719)
-- Name: collection_item collection_item_added_by_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: a1
--

ALTER TABLE ONLY public.collection_item
    ADD CONSTRAINT collection_item_added_by_user_id_fkey FOREIGN KEY (added_by_user_id) REFERENCES public.app_user(id);


--
-- TOC entry 4479 (class 2606 OID 33724)
-- Name: collection_item collection_item_collection_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: a1
--

ALTER TABLE ONLY public.collection_item
    ADD CONSTRAINT collection_item_collection_id_fkey FOREIGN KEY (collection_id) REFERENCES public.collection(id) ON DELETE CASCADE;


--
-- TOC entry 4480 (class 2606 OID 33729)
-- Name: collection_item collection_item_entity_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: a1
--

ALTER TABLE ONLY public.collection_item
    ADD CONSTRAINT collection_item_entity_id_fkey FOREIGN KEY (entity_id) REFERENCES public.entity(id) ON DELETE CASCADE;


--
-- TOC entry 4477 (class 2606 OID 33734)
-- Name: collection collection_owner_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: a1
--

ALTER TABLE ONLY public.collection
    ADD CONSTRAINT collection_owner_user_id_fkey FOREIGN KEY (owner_user_id) REFERENCES public.app_user(id);


--
-- TOC entry 4481 (class 2606 OID 33739)
-- Name: director_cluster director_cluster_created_by_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: a1
--

ALTER TABLE ONLY public.director_cluster
    ADD CONSTRAINT director_cluster_created_by_user_id_fkey FOREIGN KEY (created_by_user_id) REFERENCES public.app_user(id) ON DELETE SET NULL;


--
-- TOC entry 4482 (class 2606 OID 33744)
-- Name: director_cluster_member director_cluster_member_added_by_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: a1
--

ALTER TABLE ONLY public.director_cluster_member
    ADD CONSTRAINT director_cluster_member_added_by_user_id_fkey FOREIGN KEY (added_by_user_id) REFERENCES public.app_user(id) ON DELETE SET NULL;


--
-- TOC entry 4483 (class 2606 OID 33749)
-- Name: director_cluster_member director_cluster_member_cluster_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: a1
--

ALTER TABLE ONLY public.director_cluster_member
    ADD CONSTRAINT director_cluster_member_cluster_id_fkey FOREIGN KEY (cluster_id) REFERENCES public.director_cluster(id) ON DELETE CASCADE;


--
-- TOC entry 4484 (class 2606 OID 33754)
-- Name: director_cluster_member director_cluster_member_director_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: a1
--

ALTER TABLE ONLY public.director_cluster_member
    ADD CONSTRAINT director_cluster_member_director_id_fkey FOREIGN KEY (director_id) REFERENCES public.person(id) ON DELETE CASCADE;


--
-- TOC entry 4485 (class 2606 OID 33759)
-- Name: director_cluster_member director_cluster_member_source_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: a1
--

ALTER TABLE ONLY public.director_cluster_member
    ADD CONSTRAINT director_cluster_member_source_id_fkey FOREIGN KEY (source_id) REFERENCES public.source(id) ON DELETE SET NULL;


--
-- TOC entry 4486 (class 2606 OID 33764)
-- Name: director_cluster_translation director_cluster_translation_cluster_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: a1
--

ALTER TABLE ONLY public.director_cluster_translation
    ADD CONSTRAINT director_cluster_translation_cluster_id_fkey FOREIGN KEY (cluster_id) REFERENCES public.director_cluster(id) ON DELETE CASCADE;


--
-- TOC entry 4487 (class 2606 OID 33769)
-- Name: director_cluster_translation director_cluster_translation_language_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: a1
--

ALTER TABLE ONLY public.director_cluster_translation
    ADD CONSTRAINT director_cluster_translation_language_id_fkey FOREIGN KEY (language_id) REFERENCES public.language(id);


--
-- TOC entry 4488 (class 2606 OID 33774)
-- Name: director_influence director_influence_created_by_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: a1
--

ALTER TABLE ONLY public.director_influence
    ADD CONSTRAINT director_influence_created_by_user_id_fkey FOREIGN KEY (created_by_user_id) REFERENCES public.app_user(id);


--
-- TOC entry 4489 (class 2606 OID 33779)
-- Name: director_influence director_influence_key_film_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: a1
--

ALTER TABLE ONLY public.director_influence
    ADD CONSTRAINT director_influence_key_film_id_fkey FOREIGN KEY (key_film_id) REFERENCES public.film(id) ON DELETE SET NULL;


--
-- TOC entry 4490 (class 2606 OID 33784)
-- Name: director_influence director_influence_source_director_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: a1
--

ALTER TABLE ONLY public.director_influence
    ADD CONSTRAINT director_influence_source_director_id_fkey FOREIGN KEY (source_director_id) REFERENCES public.person(id) ON DELETE CASCADE;


--
-- TOC entry 4492 (class 2606 OID 33789)
-- Name: director_influence_source director_influence_source_influence_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: a1
--

ALTER TABLE ONLY public.director_influence_source
    ADD CONSTRAINT director_influence_source_influence_id_fkey FOREIGN KEY (influence_id) REFERENCES public.director_influence(id) ON DELETE CASCADE;


--
-- TOC entry 4493 (class 2606 OID 33794)
-- Name: director_influence_source director_influence_source_source_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: a1
--

ALTER TABLE ONLY public.director_influence_source
    ADD CONSTRAINT director_influence_source_source_id_fkey FOREIGN KEY (source_id) REFERENCES public.source(id) ON DELETE CASCADE;


--
-- TOC entry 4491 (class 2606 OID 33799)
-- Name: director_influence director_influence_target_director_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: a1
--

ALTER TABLE ONLY public.director_influence
    ADD CONSTRAINT director_influence_target_director_id_fkey FOREIGN KEY (target_director_id) REFERENCES public.person(id) ON DELETE CASCADE;


--
-- TOC entry 4495 (class 2606 OID 33804)
-- Name: entity entity_created_by_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: a1
--

ALTER TABLE ONLY public.entity
    ADD CONSTRAINT entity_created_by_user_id_fkey FOREIGN KEY (created_by_user_id) REFERENCES public.app_user(id);


--
-- TOC entry 4497 (class 2606 OID 33809)
-- Name: entity_media entity_media_added_by_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: a1
--

ALTER TABLE ONLY public.entity_media
    ADD CONSTRAINT entity_media_added_by_user_id_fkey FOREIGN KEY (added_by_user_id) REFERENCES public.app_user(id) ON DELETE SET NULL;


--
-- TOC entry 4498 (class 2606 OID 33814)
-- Name: entity_media entity_media_entity_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: a1
--

ALTER TABLE ONLY public.entity_media
    ADD CONSTRAINT entity_media_entity_id_fkey FOREIGN KEY (entity_id) REFERENCES public.entity(id) ON DELETE CASCADE;


--
-- TOC entry 4499 (class 2606 OID 33819)
-- Name: entity_media entity_media_media_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: a1
--

ALTER TABLE ONLY public.entity_media
    ADD CONSTRAINT entity_media_media_id_fkey FOREIGN KEY (media_id) REFERENCES public.media_asset(id) ON DELETE CASCADE;


--
-- TOC entry 4546 (class 2606 OID 34628)
-- Name: entity_relation entity_relation_created_by_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: a1
--

ALTER TABLE ONLY public.entity_relation
    ADD CONSTRAINT entity_relation_created_by_user_id_fkey FOREIGN KEY (created_by_user_id) REFERENCES public.app_user(id) ON DELETE SET NULL;


--
-- TOC entry 4547 (class 2606 OID 34613)
-- Name: entity_relation entity_relation_source_entity_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: a1
--

ALTER TABLE ONLY public.entity_relation
    ADD CONSTRAINT entity_relation_source_entity_id_fkey FOREIGN KEY (source_entity_id) REFERENCES public.entity(id) ON DELETE CASCADE;


--
-- TOC entry 4548 (class 2606 OID 34623)
-- Name: entity_relation entity_relation_source_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: a1
--

ALTER TABLE ONLY public.entity_relation
    ADD CONSTRAINT entity_relation_source_id_fkey FOREIGN KEY (source_id) REFERENCES public.source(id) ON DELETE SET NULL;


--
-- TOC entry 4549 (class 2606 OID 34618)
-- Name: entity_relation entity_relation_target_entity_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: a1
--

ALTER TABLE ONLY public.entity_relation
    ADD CONSTRAINT entity_relation_target_entity_id_fkey FOREIGN KEY (target_entity_id) REFERENCES public.entity(id) ON DELETE CASCADE;


--
-- TOC entry 4500 (class 2606 OID 33824)
-- Name: entity_taxonomy entity_taxonomy_entity_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: a1
--

ALTER TABLE ONLY public.entity_taxonomy
    ADD CONSTRAINT entity_taxonomy_entity_id_fkey FOREIGN KEY (entity_id) REFERENCES public.entity(id) ON DELETE CASCADE;


--
-- TOC entry 4501 (class 2606 OID 33829)
-- Name: entity_taxonomy entity_taxonomy_source_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: a1
--

ALTER TABLE ONLY public.entity_taxonomy
    ADD CONSTRAINT entity_taxonomy_source_id_fkey FOREIGN KEY (source_id) REFERENCES public.source(id);


--
-- TOC entry 4502 (class 2606 OID 33834)
-- Name: entity_taxonomy entity_taxonomy_term_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: a1
--

ALTER TABLE ONLY public.entity_taxonomy
    ADD CONSTRAINT entity_taxonomy_term_id_fkey FOREIGN KEY (term_id) REFERENCES public.taxonomy_term(id) ON DELETE CASCADE;


--
-- TOC entry 4503 (class 2606 OID 33839)
-- Name: entity_translation entity_translation_entity_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: a1
--

ALTER TABLE ONLY public.entity_translation
    ADD CONSTRAINT entity_translation_entity_id_fkey FOREIGN KEY (entity_id) REFERENCES public.entity(id) ON DELETE CASCADE;


--
-- TOC entry 4504 (class 2606 OID 33844)
-- Name: entity_translation entity_translation_language_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: a1
--

ALTER TABLE ONLY public.entity_translation
    ADD CONSTRAINT entity_translation_language_id_fkey FOREIGN KEY (language_id) REFERENCES public.language(id);


--
-- TOC entry 4496 (class 2606 OID 33849)
-- Name: entity entity_updated_by_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: a1
--

ALTER TABLE ONLY public.entity
    ADD CONSTRAINT entity_updated_by_user_id_fkey FOREIGN KEY (updated_by_user_id) REFERENCES public.app_user(id);


--
-- TOC entry 4505 (class 2606 OID 33854)
-- Name: entity_version entity_version_author_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: a1
--

ALTER TABLE ONLY public.entity_version
    ADD CONSTRAINT entity_version_author_user_id_fkey FOREIGN KEY (author_user_id) REFERENCES public.app_user(id);


--
-- TOC entry 4506 (class 2606 OID 33859)
-- Name: entity_version entity_version_entity_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: a1
--

ALTER TABLE ONLY public.entity_version
    ADD CONSTRAINT entity_version_entity_id_fkey FOREIGN KEY (entity_id) REFERENCES public.entity(id) ON DELETE CASCADE;


--
-- TOC entry 4507 (class 2606 OID 33864)
-- Name: entity_version entity_version_language_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: a1
--

ALTER TABLE ONLY public.entity_version
    ADD CONSTRAINT entity_version_language_id_fkey FOREIGN KEY (language_id) REFERENCES public.language(id);


--
-- TOC entry 4508 (class 2606 OID 33869)
-- Name: entity_version entity_version_source_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: a1
--

ALTER TABLE ONLY public.entity_version
    ADD CONSTRAINT entity_version_source_id_fkey FOREIGN KEY (source_id) REFERENCES public.source(id);


--
-- TOC entry 4509 (class 2606 OID 33874)
-- Name: favorite favorite_entity_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: a1
--

ALTER TABLE ONLY public.favorite
    ADD CONSTRAINT favorite_entity_id_fkey FOREIGN KEY (entity_id) REFERENCES public.entity(id) ON DELETE CASCADE;


--
-- TOC entry 4510 (class 2606 OID 33879)
-- Name: favorite favorite_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: a1
--

ALTER TABLE ONLY public.favorite
    ADD CONSTRAINT favorite_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.app_user(id) ON DELETE CASCADE;


--
-- TOC entry 4511 (class 2606 OID 33884)
-- Name: film film_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: a1
--

ALTER TABLE ONLY public.film
    ADD CONSTRAINT film_id_fkey FOREIGN KEY (id) REFERENCES public.entity(id) ON DELETE CASCADE;


--
-- TOC entry 4512 (class 2606 OID 33889)
-- Name: film film_original_language_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: a1
--

ALTER TABLE ONLY public.film
    ADD CONSTRAINT film_original_language_id_fkey FOREIGN KEY (original_language_id) REFERENCES public.language(id);


--
-- TOC entry 4513 (class 2606 OID 33894)
-- Name: film_person film_person_film_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: a1
--

ALTER TABLE ONLY public.film_person
    ADD CONSTRAINT film_person_film_id_fkey FOREIGN KEY (film_id) REFERENCES public.film(id) ON DELETE CASCADE;


--
-- TOC entry 4514 (class 2606 OID 33899)
-- Name: film_person film_person_person_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: a1
--

ALTER TABLE ONLY public.film_person
    ADD CONSTRAINT film_person_person_id_fkey FOREIGN KEY (person_id) REFERENCES public.person(id) ON DELETE CASCADE;


--
-- TOC entry 4515 (class 2606 OID 33904)
-- Name: film_person film_person_source_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: a1
--

ALTER TABLE ONLY public.film_person
    ADD CONSTRAINT film_person_source_id_fkey FOREIGN KEY (source_id) REFERENCES public.source(id);


--
-- TOC entry 4543 (class 2606 OID 34578)
-- Name: film_studio film_studio_film_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: a1
--

ALTER TABLE ONLY public.film_studio
    ADD CONSTRAINT film_studio_film_id_fkey FOREIGN KEY (film_id) REFERENCES public.film(id) ON DELETE CASCADE;


--
-- TOC entry 4544 (class 2606 OID 34588)
-- Name: film_studio film_studio_source_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: a1
--

ALTER TABLE ONLY public.film_studio
    ADD CONSTRAINT film_studio_source_id_fkey FOREIGN KEY (source_id) REFERENCES public.source(id) ON DELETE SET NULL;


--
-- TOC entry 4545 (class 2606 OID 34583)
-- Name: film_studio film_studio_studio_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: a1
--

ALTER TABLE ONLY public.film_studio
    ADD CONSTRAINT film_studio_studio_id_fkey FOREIGN KEY (studio_id) REFERENCES public.studio(id) ON DELETE CASCADE;


--
-- TOC entry 4516 (class 2606 OID 33909)
-- Name: media_asset media_asset_uploaded_by_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: a1
--

ALTER TABLE ONLY public.media_asset
    ADD CONSTRAINT media_asset_uploaded_by_user_id_fkey FOREIGN KEY (uploaded_by_user_id) REFERENCES public.app_user(id) ON DELETE SET NULL;


--
-- TOC entry 4494 (class 2606 OID 33914)
-- Name: person person_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: a1
--

ALTER TABLE ONLY public.person
    ADD CONSTRAINT person_id_fkey FOREIGN KEY (id) REFERENCES public.entity(id) ON DELETE CASCADE;


--
-- TOC entry 4517 (class 2606 OID 33919)
-- Name: search_history search_history_clicked_entity_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: a1
--

ALTER TABLE ONLY public.search_history
    ADD CONSTRAINT search_history_clicked_entity_id_fkey FOREIGN KEY (clicked_entity_id) REFERENCES public.entity(id) ON DELETE SET NULL;


--
-- TOC entry 4518 (class 2606 OID 33924)
-- Name: search_history search_history_language_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: a1
--

ALTER TABLE ONLY public.search_history
    ADD CONSTRAINT search_history_language_id_fkey FOREIGN KEY (language_id) REFERENCES public.language(id);


--
-- TOC entry 4519 (class 2606 OID 33929)
-- Name: search_history search_history_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: a1
--

ALTER TABLE ONLY public.search_history
    ADD CONSTRAINT search_history_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.app_user(id) ON DELETE SET NULL;


--
-- TOC entry 4520 (class 2606 OID 33934)
-- Name: source source_language_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: a1
--

ALTER TABLE ONLY public.source
    ADD CONSTRAINT source_language_id_fkey FOREIGN KEY (language_id) REFERENCES public.language(id);


--
-- TOC entry 4540 (class 2606 OID 34545)
-- Name: studio studio_parent_studio_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: a1
--

ALTER TABLE ONLY public.studio
    ADD CONSTRAINT studio_parent_studio_id_fkey FOREIGN KEY (parent_studio_id) REFERENCES public.studio(id) ON DELETE SET NULL;


--
-- TOC entry 4541 (class 2606 OID 34563)
-- Name: studio_translation studio_translation_language_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: a1
--

ALTER TABLE ONLY public.studio_translation
    ADD CONSTRAINT studio_translation_language_id_fkey FOREIGN KEY (language_id) REFERENCES public.language(id);


--
-- TOC entry 4542 (class 2606 OID 34558)
-- Name: studio_translation studio_translation_studio_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: a1
--

ALTER TABLE ONLY public.studio_translation
    ADD CONSTRAINT studio_translation_studio_id_fkey FOREIGN KEY (studio_id) REFERENCES public.studio(id) ON DELETE CASCADE;


--
-- TOC entry 4521 (class 2606 OID 33939)
-- Name: taxonomy_term taxonomy_term_parent_term_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: a1
--

ALTER TABLE ONLY public.taxonomy_term
    ADD CONSTRAINT taxonomy_term_parent_term_id_fkey FOREIGN KEY (parent_term_id) REFERENCES public.taxonomy_term(id);


--
-- TOC entry 4522 (class 2606 OID 33944)
-- Name: taxonomy_term_translation taxonomy_term_translation_language_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: a1
--

ALTER TABLE ONLY public.taxonomy_term_translation
    ADD CONSTRAINT taxonomy_term_translation_language_id_fkey FOREIGN KEY (language_id) REFERENCES public.language(id);


--
-- TOC entry 4523 (class 2606 OID 33949)
-- Name: taxonomy_term_translation taxonomy_term_translation_term_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: a1
--

ALTER TABLE ONLY public.taxonomy_term_translation
    ADD CONSTRAINT taxonomy_term_translation_term_id_fkey FOREIGN KEY (term_id) REFERENCES public.taxonomy_term(id) ON DELETE CASCADE;


--
-- TOC entry 4554 (class 2606 OID 34698)
-- Name: user_note user_note_entity_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: a1
--

ALTER TABLE ONLY public.user_note
    ADD CONSTRAINT user_note_entity_id_fkey FOREIGN KEY (entity_id) REFERENCES public.entity(id) ON DELETE CASCADE;


--
-- TOC entry 4555 (class 2606 OID 34693)
-- Name: user_note user_note_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: a1
--

ALTER TABLE ONLY public.user_note
    ADD CONSTRAINT user_note_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.app_user(id) ON DELETE CASCADE;


--
-- TOC entry 4550 (class 2606 OID 34649)
-- Name: user_rating user_rating_entity_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: a1
--

ALTER TABLE ONLY public.user_rating
    ADD CONSTRAINT user_rating_entity_id_fkey FOREIGN KEY (entity_id) REFERENCES public.entity(id) ON DELETE CASCADE;


--
-- TOC entry 4551 (class 2606 OID 34644)
-- Name: user_rating user_rating_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: a1
--

ALTER TABLE ONLY public.user_rating
    ADD CONSTRAINT user_rating_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.app_user(id) ON DELETE CASCADE;


--
-- TOC entry 4552 (class 2606 OID 34673)
-- Name: user_watchlist user_watchlist_entity_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: a1
--

ALTER TABLE ONLY public.user_watchlist
    ADD CONSTRAINT user_watchlist_entity_id_fkey FOREIGN KEY (entity_id) REFERENCES public.entity(id) ON DELETE CASCADE;


--
-- TOC entry 4553 (class 2606 OID 34668)
-- Name: user_watchlist user_watchlist_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: a1
--

ALTER TABLE ONLY public.user_watchlist
    ADD CONSTRAINT user_watchlist_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.app_user(id) ON DELETE CASCADE;


--
-- TOC entry 4524 (class 2606 OID 33954)
-- Name: view_history view_history_entity_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: a1
--

ALTER TABLE ONLY public.view_history
    ADD CONSTRAINT view_history_entity_id_fkey FOREIGN KEY (entity_id) REFERENCES public.entity(id) ON DELETE CASCADE;


--
-- TOC entry 4525 (class 2606 OID 33959)
-- Name: view_history view_history_language_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: a1
--

ALTER TABLE ONLY public.view_history
    ADD CONSTRAINT view_history_language_id_fkey FOREIGN KEY (language_id) REFERENCES public.language(id);


--
-- TOC entry 4526 (class 2606 OID 33964)
-- Name: view_history view_history_referrer_entity_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: a1
--

ALTER TABLE ONLY public.view_history
    ADD CONSTRAINT view_history_referrer_entity_id_fkey FOREIGN KEY (referrer_entity_id) REFERENCES public.entity(id) ON DELETE SET NULL;


--
-- TOC entry 4527 (class 2606 OID 33969)
-- Name: view_history view_history_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: a1
--

ALTER TABLE ONLY public.view_history
    ADD CONSTRAINT view_history_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.app_user(id) ON DELETE SET NULL;


-- Completed on 2026-05-03 23:28:21 +07

--
-- PostgreSQL database dump complete
--

